---
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "80:9090"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "443:3000"
    volumes:
      - grafana_data:/var/lib/grafana
  snmp-exporter:
    image: prom/snmp-exporter
    container_name: snmp-exporter
    ports:
      - "9116:9116"
    volumes:
      - ./snmp/snmp.yml:/etc/snmp_exporter/snmp.yml

  blackbox-exporter:
    image: prom/blackbox-exporter
    ports:
      - "9115:9115"
    restart: unless-stopped


volumes:
  prometheus_data:
  grafana_data:
  snmp-exporter:
  blackbox-exporter:

