global:
   scrape_interval: 5s # Fréquence de collecte des métriques

scrape_configs:
   - job_name: 'nginx'
     static_configs:
        - targets: ['10.200.2.10:9113']
   - job_name: 'check-pages'
     metrics_path: /probe
     params:
        module: [http_2xx] # Vérifie que la page répond avec un code HTTP 2xx
     static_configs:
        - targets:
             - http://10.200.2.10:800/page1.html
             - http://10.200.2.10:800/page2.html
             - http://10.200.2.10:800/page3.html
     relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox-exporter:9115
   - job_name: 'prometheus'
     static_configs:
        - targets: ['localhost:9090']
   - job_name: 'node-exporter'
     static_configs:
        - targets: ['10.200.2.10:9100']
   - job_name: 'debit'
     scrape_interval: 5s
     static_configs:
        - targets: ['10.200.2.254', '10.200.2.253'] # IP des routeurs
          labels:
             group: 'router'
     metrics_path: /snmp
     params:
        module: [if_mib]
     relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: snmp-exporter:9116
